apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
      - name: main
        ports:
        - containerPort: 8080
        volumeMounts:
        # The logs folder needs to be RW because that's where the pidfile 'httpd.pid' goes.
        # (the logs go to stdout, not to files)
        - mountPath: /usr/local/apache2/logs/
          name: logs-emptydir
        securityContext:
          runAsUser: 65532
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: 12Mi
          limits:
            cpu: "1000m"
            memory: "128Mi"
            ephemeral-storage: 64Mi
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 100
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      volumes:
        - name: logs-emptydir
          emptyDir:
            sizeLimit: 10Mi
