apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  # same as default server value for replicas, but set explicitly in config so that apply restores it if modified
  replicas: 1
  # same as default server values for strategy, but set explicitly in config as per docs recommendation to
  # avoid errors if we ever change it due to fields that are defaulted based on the values of other fields
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      restartPolicy: Always
