apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridmonitor-app
  labels:
    name: gridmonitor-app
    version: "1"
    app.kubernetes.io/component: gridsuite-apache
    gridsuite.org/apache-gridapp: "true"
spec:
  selector:
    matchLabels:
      name: gridmonitor-app
  template:
    metadata:
      labels:
        name: gridmonitor-app
    spec:
      containers:
      - name: main
        image: docker.io/gridsuite/gridmonitor-app:latest
        volumeMounts:
        - mountPath: /opt/bitnami/apache/htdocs/gridmonitor/env.json
          subPath: env.json
          name: gridapps-env-configmap-volume
        - mountPath: /opt/bitnami/apache/htdocs/gridmonitor/idpSettings.json
          subPath: idpSettings.json
          name: gridmonitor-app-configmap-volume
      volumes:
        - name: gridmonitor-app-configmap-volume
          configMap:
            name: gridmonitor-app-configmap
