# Copy pasted gridapps-metadata app-httpd.conf just to configure the openid-configuration MIME type
<VirtualHost *:8080>
  DocumentRoot "/usr/local/apache2/htdocs"
  <Directory "/usr/local/apache2/htdocs">

    # no-cache+digest-etags: revalidate everytime with stable Etags accross loadbalanced servers.
    #   "FileETag Digest" is acceptable here because we have only small files on this server so
    #   having to read the full content of the file instead of just the filesystem
    #   metadata is not prohibitedly expensive. A better alternative would be to find
    #   a way to have stable filesystem metadata on all servers because:
    #   - accessing file system metadata is a lot less expensive.
    #   - contrary to apache httpd, nginx doesn't have an option to change the ETag
    #     generation method and always uses the filesystem metadata (size, mtime),
    #     so using "FileEtag Digest" locks us in with apache httpd.
    #   NOTE: this doesn't apply to files in the image (their filesystem metadata
    #   is the same because it's from the image), only to mounted files (bind mount
    #   or volume mount in docker compose, configmap in kubernetes)
    Header set Cache-Control "no-cache"
    FileETag Digest

  </Directory>

  # Need to be forced as it doesn't end with .json, our client complains
  # This is used for the supervision identity provider
  <FilesMatch "^openid-configuration$">
      ForceType application/json
  </FilesMatch>
</VirtualHost>
