# Nb of LF concurrent processes - should be in-sync with loadflow.run.loadflowGroup queue concurrency
computation-local:
  available-core: 4

load-flow-default-parameters:
  voltageInitMode: DC_VALUES
  phaseShifterRegulationOn: true
  twtSplitShuntAdmittance: true
  dcUseTransformerRatio: false
  countriesToBalance:
    - FR

#TODO: remove writeReferenceTerminals parameter override when ReferenceTerminals extension is implemented
open-loadflow-default-parameters:
  writeReferenceTerminals: false
  slackDistributionFailureBehavior : FAIL
