#!/usr/bin/env bash
#
# war-deploy.sh — Build GridSuite microservices as WAR files for docker-compose.
#                 Zero modifications to original server source files.
#
# Word of Caution, the whole script with comments (except this sentence)
# has been generated by opus4.6 without much look at the details.
#
# Usage:
#   ./war-deploy.sh [OPTIONS]
#
# Options:
#   --only SRV         Only process this server (repeatable)
#   --help             Show this help
#
# Strategy ("wrapper POM" approach):
#   Instead of modifying original Spring Boot server sources to produce WAR files,
#   we generate lightweight wrapper Maven projects that:
#   1. Depend on the original server's classes JAR (available because powsybl-parent-ws
#      configures spring-boot-maven-plugin with <classifier>exec</classifier>, so
#      `mvn install` installs both the executable fat JAR and a plain classes JAR)
#   2. Provide a SpringBootServletInitializer subclass (required for WAR deployment)
#   3. Set spring.config.additional-location for per-WAR config overrides
#   4. Package as WAR with <finalName> = desired context path
#
#   This keeps all server submodules UNMODIFIED while producing deployable WARs.
#
# Future improvements:
#   - Move shared JARs (Spring, Hibernate, powsybl-commons, etc.) into Tomcat's
#     lib/ directory so they are loaded once by the common classloader. This would
#     significantly reduce Metaspace usage (each WAR currently loads its own copy
#     of every dependency class).
#   - Reduce duplication in config override generation: many servers share the same
#     service references (e.g. network-store, report-server). A template or merge
#     system could replace per-server YAML generation.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGGREGATOR_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
SERVERS_DIR="$AGGREGATOR_ROOT/backend/servers"
WRAPPERS_DIR="$SCRIPT_DIR/gen/war-wrappers"
WEBAPPS_DIR="$SCRIPT_DIR/gen/wars"
CONFIG_DIR="$SCRIPT_DIR/gen/externalized-war-configs"

# Base URL used inside docker network (container-to-container)
TOMCAT_BASE_URL="http://tomcat:8080"

# Defaults
ONLY_SERVERS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --only)         ONLY_SERVERS+=("$2"); shift 2 ;;
        --help)         sed -n '2,/^$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

log() { echo -e "\033[1;34m[WAR]\033[0m $*"; }
err() { echo -e "\033[1;31m[ERR]\033[0m $*" >&2; }

# ===========================================================================
# SERVER MANIFEST
# Format: context_name|server_folder|pom_subpath|app_class_fqn
#
# context_name: WAR filename / Tomcat context path
# server_folder: folder under backend/servers/
# pom_subpath: submodule path within server_folder (empty = root)
# app_class_fqn: fully qualified Application class name
# Lines starting with # are disabled. Uncomment to include in the build.
# ===========================================================================
MANIFEST=(
"actions-server|actions-server||org.gridsuite.actions.server.ActionsApplication"
#"balances-adjustment-server|balances-adjustment-server||org.gridsuite.balances.adjustment.server.BalancesAdjustmentApplication"
#"case-import-server|case-import-server||org.gridsuite.caseimport.server.CaseImportApplication"
#"case-validation-server|case-validation-server||org.gridsuite.casevalidation.server.CaseValidationApplication"
#"cgmes-boundary-server|cgmes-boundary-server||org.gridsuite.cgmes.boundary.server.CgmesBoundaryApplication"
#"cgmes-gl-server|cgmes-gl-server||org.gridsuite.cgmes.gl.server.CgmesGlApplication"
"directory-server|directory-server||org.gridsuite.directory.server.DirectoryApplication"
#"dynamic-mapping-server|dynamic-mapping-server||org.gridsuite.mapping.server.MappingApplication"
#"dynamic-margin-calculation-server|dynamic-margin-calculation-server||org.gridsuite.dynamicmargincalculation.server.DynamicMarginCalculationApplication"
#"dynamic-security-analysis-server|dynamic-security-analysis-server||org.gridsuite.dynamicsecurityanalysis.server.DynamicSecurityAnalysisApplication"
#"dynamic-simulation-server|dynamic-simulation-server||org.gridsuite.ds.server.DynamicSimulationApplication"
"explore-server|explore-server||org.gridsuite.explore.server.ExploreApplication"
"filter-server|filter-server||org.gridsuite.filter.server.FilterApplication"
"geo-data-server|geo-data-server||org.gridsuite.geodata.server.GeoDataApplication"
"loadflow-server|loadflow-server||org.gridsuite.loadflow.server.LoadFlowApplication"
#"merge-orchestrator-server|merge-orchestrator-server||org.gridsuite.merge.orchestrator.server.MergeOrchestratorApplication"
"network-map-server|network-map-server||org.gridsuite.network.map.NetworkMapApplication"
"network-modification-server|network-modification-server||org.gridsuite.modification.server.NetworkModificationApplication"
"network-store-server|powsybl-network-store-server|network-store-server|com.powsybl.network.store.server.NetworkStoreApplication"
#"odre-server|odre-server||org.gridsuite.odre.server.OdreApplication"
"case-server|powsybl-case-server||com.powsybl.caseserver.CaseApplication"
"network-conversion-server|powsybl-network-conversion-server||com.powsybl.network.conversion.server.NetworkConversionApplication"
"single-line-diagram-server|powsybl-single-line-diagram-server||com.powsybl.sld.server.SingleLineDiagramApplication"
"report-server|report-server||org.gridsuite.report.server.ReportApplication"
"security-analysis-server|security-analysis-server||org.gridsuite.securityanalysis.server.SecurityAnalysisApplication"
"sensitivity-analysis-server|sensitivity-analysis-server||org.gridsuite.sensitivityanalysis.server.SensitivityAnalysisApplication"
"shortcircuit-server|shortcircuit-server||org.gridsuite.shortcircuit.server.ShortCircuitApplication"
"study-config-server|study-config-server||org.gridsuite.studyconfig.server.StudyConfigApplication"
"study-server|study-server||org.gridsuite.study.server.StudyApplication"
#"timeseries-server|timeseries-server||org.gridsuite.timeseries.server.TimeSeriesApplication"
"user-admin-server|user-admin-server||org.gridsuite.useradmin.server.UserAdminApplication"
"user-identity-server|user-identity-oidc-replication-server||org.gridsuite.useridentity.oidcreplication.server.UserIdentityOidcReplicationApplication"
"voltage-init-server|voltage-init-server||org.gridsuite.voltageinit.server.VoltageInitApplication"
)

# Filter out commented entries (lines starting with #)
_filtered=()
for _e in "${MANIFEST[@]}"; do
    [[ "$_e" =~ ^# ]] || _filtered+=("$_e")
done
MANIFEST=("${_filtered[@]}")
unset _filtered _e

should_process() {
    local ctx="$1"
    if [[ ${#ONLY_SERVERS[@]} -gt 0 ]]; then
        for s in "${ONLY_SERVERS[@]}"; do
            [[ "$s" == "$ctx" ]] && return 0
        done
        return 1
    fi
    return 0
}

# Resolve a service key to its base-uri.
# Trailing slash is required: clients use UriComponentsBuilder.fromUriString(baseUri)
# which concatenates paths like "v1/networks/..." directly after the base URI.
# Without trailing slash: "http://tomcat:8080/network-store-serverv1/..." (broken)
# With trailing slash:    "http://tomcat:8080/network-store-server/v1/..." (correct)
resolve_base_uri() {
    local svc_key="$1"
    echo "${TOMCAT_BASE_URL}/${svc_key}/"
}

# Generate per-WAR config override with base-uri values pointing to Tomcat.
# Since we disable the "local" profile, we only need base-uri overrides in application.yml.
# Reads the original application-local file to discover which services are referenced,
# then generates a clean application.yml with only the base-uri section.
generate_local_config_override() {
    local ctx="$1"
    local server_folder="$2"
    local pom_subpath="$3"
    local wrapper_dir="$4"

    local module_dir="$SERVERS_DIR/$server_folder"
    [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

    # Find the original application-local file to discover service references
    local orig_file=""
    for ext in yaml yml; do
        if [[ -f "$module_dir/src/main/resources/application-local.$ext" ]]; then
            orig_file="$module_dir/src/main/resources/application-local.$ext"
            break
        fi
    done
    [[ -z "$orig_file" ]] && return 0

    # Detect which format gridsuite: services: uses (list-style vs map-style)
    local uses_list_style=false
    if grep -qE '^\s+-\s*(name:|$)' "$orig_file" 2>/dev/null; then
        uses_list_style=true
    fi

    # Extract service keys referenced in the file
    local powsybl_services=() gridsuite_services=()
    local current_section=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^powsybl: ]]; then
            current_section="powsybl"
        elif [[ "$line" =~ ^gridsuite: ]]; then
            current_section="gridsuite"
        elif [[ ! "$line" =~ ^[[:space:]] && ! "$line" =~ ^# && -n "$line" ]]; then
            current_section="other"
        fi

        # Map-style key: "    server-name:"
        if [[ "$line" =~ ^[[:space:]]{4}([a-z][a-z0-9-]+):$ ]]; then
            local key="${BASH_REMATCH[1]}"
            if [[ "$current_section" == "powsybl" ]]; then
                powsybl_services+=("$key")
            elif [[ "$current_section" == "gridsuite" ]]; then
                gridsuite_services+=("$key")
            fi
        fi
        # List-style: "- name: xxx" or "    name: xxx"
        if [[ "$line" =~ ^[[:space:]]+-[[:space:]]*name:[[:space:]]*(.+) ]]; then
            local key="${BASH_REMATCH[1]}"
            key="${key%%[[:space:]]}"
            [[ "$current_section" == "gridsuite" ]] && gridsuite_services+=("$key")
        elif [[ "$line" =~ ^[[:space:]]+name:[[:space:]]*(.+) && "$current_section" == "gridsuite" ]]; then
            local key="${BASH_REMATCH[1]}"
            key="${key%%[[:space:]]}"
            gridsuite_services+=("$key")
        fi
    done < "$orig_file"

    # If no services referenced, no config needed
    if [[ ${#powsybl_services[@]} -eq 0 && ${#gridsuite_services[@]} -eq 0 ]]; then
        return 0
    fi

    local out_file="$CONFIG_DIR/$ctx/application.yml"
    mkdir -p "$CONFIG_DIR/$ctx"

    local output=""

    # Generate powsybl: services: section (always map-style)
    if [[ ${#powsybl_services[@]} -gt 0 ]]; then
        output+="powsybl:"$'\n'
        output+="  services:"$'\n'
        for svc in "${powsybl_services[@]}"; do
            local uri
            uri=$(resolve_base_uri "$svc")
            output+="    ${svc}:"$'\n'
            output+="      base-uri: ${uri}"$'\n'
        done
    fi

    # Generate gridsuite: services: section
    if [[ ${#gridsuite_services[@]} -gt 0 ]]; then
        [[ -n "$output" ]] && output+=$'\n'
        output+="gridsuite:"$'\n'
        output+="  services:"$'\n'
        if $uses_list_style; then
            for svc in "${gridsuite_services[@]}"; do
                local uri
                uri=$(resolve_base_uri "$svc")
                output+="    -"$'\n'
                output+="      name: ${svc}"$'\n'
                output+="      base-uri: ${uri}"$'\n'
            done
        else
            for svc in "${gridsuite_services[@]}"; do
                local uri
                uri=$(resolve_base_uri "$svc")
                output+="    ${svc}:"$'\n'
                output+="      base-uri: ${uri}"$'\n'
            done
        fi
    fi

    echo -n "$output" > "$out_file"
}

# ===========================================================================
# PHASE 1: GENERATE WRAPPER PROJECTS
# ===========================================================================
generate_wrappers() {
    log "=== Generating wrapper projects ==="
    rm -rf "$WRAPPERS_DIR"
    mkdir -p "$WRAPPERS_DIR"

    # Detect gridsuite-dependencies BOM version
    local first_entry="${MANIFEST[0]}"
    IFS='|' read -r _ctx first_folder first_sub _ <<< "$first_entry"
    local first_dir="$SERVERS_DIR/$first_folder"
    [[ -n "$first_sub" ]] && first_dir="$first_dir/$first_sub"
    local gridsuite_deps_version
    gridsuite_deps_version=$(grep -m1 "gridsuite-dependencies.version" "$first_dir/pom.xml" 2>/dev/null | sed 's/.*>\(.*\)<.*/\1/' || true)
    [[ -z "$gridsuite_deps_version" ]] && gridsuite_deps_version="50.0.0"
    log "  gridsuite-dependencies version: $gridsuite_deps_version"

    local modules=""

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local module_dir="$SERVERS_DIR/$server_folder"
        [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

        # Get groupId, artifactId, version from the server's pom
        local group_id artifact_id version parent_group parent_version

        parent_group=$(sed -n '/<parent>/,/<\/parent>/p' "$module_dir/pom.xml" | grep '<groupId>' | sed 's/.*<groupId>//;s/<.*//' | tr -d ' ')
        parent_version=$(sed -n '/<parent>/,/<\/parent>/p' "$module_dir/pom.xml" | grep '<version>' | sed 's/.*<version>//;s/<.*//' | tr -d ' ')
        artifact_id=$(sed -n '/<\/parent>/,$ p' "$module_dir/pom.xml" | grep -m1 '<artifactId>' | sed 's/.*<artifactId>//;s/<.*//' | tr -d ' ')
        version=$(sed -n '/<\/parent>/,/<\(build\|dependencies\|dependencyManagement\|properties\)>/ p' "$module_dir/pom.xml" | grep -m1 '<version>' | sed 's/.*<version>//;s/<.*//' | tr -d ' ' || true)
        group_id=$(sed -n '/<\/parent>/,/<\(build\|dependencies\|dependencyManagement\|properties\)>/ p' "$module_dir/pom.xml" | grep -m1 '<groupId>' | sed 's/.*<groupId>//;s/<.*//' | tr -d ' ' || true)

        # Fall back to parent values if not specified at project level
        [[ -z "$group_id" ]] && group_id="$parent_group"
        [[ -z "$version" ]] && version="$parent_version"

        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        mkdir -p "$wrapper_dir/src/main/java/org/gridsuite/war"

        # Generate WarInitializer.java
        # Sets spring.config.additional-location to load per-WAR base-uri overrides from
        # an external directory (/config/<ctx>/application.yml). "optional:" prefix means
        # servers with no service references (e.g. report-server) won't fail if the
        # directory doesn't exist. This is the Spring Boot guaranteed way to override
        # config — additional-location properties always win over classpath configs.
        local simple_class="${app_class##*.}"
        local initializer_class="${simple_class/Application/WarInitializer}"
        cat > "$wrapper_dir/src/main/java/org/gridsuite/war/${initializer_class}.java" << JAVA
package org.gridsuite.war;

import ${app_class};
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ${initializer_class} extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(${simple_class}.class)
            .properties("spring.config.additional-location=optional:file:/config/${ctx}/");
    }
}
JAVA

        # Generate wrapper pom.xml
        local extra_deps=""
        # antlr4 version override: these servers depend on powsybl-open-loadflow which
        # pulls in graphviz-builder → antlr4:4.5.1. But Spring Data JPA's HqlLexer was
        # compiled with antlr4 4.13.0 (ATN version 4). The old antlr4-4.5.1.jar contains
        # ATNDeserializer that only understands ATN version 3, causing:
        #   InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 4
        # Fix: force antlr4 (the full tool jar, which includes the runtime) to 4.13.0.
        case "$ctx" in
            loadflow-server|security-analysis-server|sensitivity-analysis-server|network-modification-server)
                extra_deps='
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4</artifactId>
            <version>4.13.0</version>
        </dependency>'
                ;;
        esac

        cat > "$wrapper_dir/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.gridsuite.war</groupId>
        <artifactId>war-wrappers</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>${ctx}-war</artifactId>
    <packaging>war</packaging>

    <dependencies>
        <dependency>
            <groupId>${group_id}</groupId>
            <artifactId>${artifact_id}</artifactId>
            <version>${version}</version>
        </dependency>${extra_deps}
    </dependencies>

    <build>
        <finalName>${ctx}</finalName>
    </build>
</project>
POM

        modules="$modules        <module>$ctx</module>\n"
        log "  ${ctx}-war -> $module_dir"
    done

    # Generate reactor parent pom
    cat > "$WRAPPERS_DIR/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gridsuite.war</groupId>
    <artifactId>war-wrappers</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Import gridsuite-dependencies BOM: manages com.powsybl:*, Spring Boot,
                 software.amazon.awssdk:* versions to match what servers are compiled against.
                 Without this, Maven "nearest wins" rule would resolve older transitive
                 versions (e.g. powsybl-commons 7.0.1 instead of 7.1.1) causing
                 NoSuchMethodError at runtime. -->
            <dependency>
                <groupId>org.gridsuite</groupId>
                <artifactId>gridsuite-dependencies</artifactId>
                <version>${gridsuite_deps_version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Common to all wrappers -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <modules>
$(echo -e "$modules")    </modules>
</project>
POM

    # Generate per-WAR config overrides directly into gen/externalized-war-configs/
    rm -rf "$CONFIG_DIR"
    log "=== Generating externalized WAR additional-configs ==="
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue
        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        generate_local_config_override "$ctx" "$server_folder" "$pom_subpath" "$wrapper_dir"
    done
    ls -1 "$CONFIG_DIR"/*/* 2>/dev/null || true


}

# ===========================================================================
# PHASE 2: BUILD ALL (SINGLE REACTOR)
# Builds ALL server source modules + wrapper projects in one Maven invocation.
# Server source modules are added to the reactor so that their classes JARs
# are available in the local repo for wrapper dependency resolution.
# -T2.0C = 2 threads per CPU core for parallel module builds.
# ===========================================================================
build_wars() {
    # Prefer mvnd (Maven Daemon) for faster builds; fall back to mvn -q
    local mvn_cmd
    if command -v mvnd &>/dev/null; then
        mvn_cmd="mvnd"
        log "=== Building all with mvnd ==="
    else
        mvn_cmd="mvn -T2.0C -q"
        log "=== Building all with mvn (mvnd not found, using -T2.0C -q) ==="
    fi

    # Add server source modules to reactor POM for a single build
    local server_modules=""
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local rel_path="../../../../../../backend/servers/$server_folder"
        [[ -n "$pom_subpath" ]] && rel_path="$rel_path/$pom_subpath"
        server_modules+="        <module>${rel_path}</module>\n"
    done

    # Inject server modules into reactor POM (before wrapper modules)
    local wrapper_pom="$WRAPPERS_DIR/pom.xml"
    sed -i "s|    <modules>|    <modules>\n        <!-- Server sources -->\n${server_modules}        <!-- WAR wrappers -->|" "$wrapper_pom"

    log "Running: $mvn_cmd package -DskipTests -f $WRAPPERS_DIR/pom.xml"
    (cd "$WRAPPERS_DIR" && $mvn_cmd package -DskipTests) || {
        err "Reactor build failed"
        return 1
    }

    # Verify
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue
        if [[ ! -f "$WRAPPERS_DIR/$ctx/target/${ctx}.war" ]]; then
            err "Missing: $WRAPPERS_DIR/$ctx/target/${ctx}.war"
        fi
    done
}

# ===========================================================================
# PHASE 3: COPY WARS TO DOCKER-COMPOSE MOUNT DIR
# ===========================================================================
deploy_to_compose_dirs() {
    log "=== Copying WARs to gen/wars/ ==="
    rm -rf "$WEBAPPS_DIR"
    mkdir -p "$WEBAPPS_DIR"

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local war="$WRAPPERS_DIR/$ctx/target/${ctx}.war"
        if [[ -f "$war" ]]; then
            cp "$war" "$WEBAPPS_DIR/"
        else
            err "Missing: $war"
        fi
    done

    ls -1 "$WEBAPPS_DIR"/*.war 2>/dev/null
    echo ""
    echo "Folders gen/wars/ and gen/externalized-war-configs/ ready for \$ docker compose up"
}

# ===========================================================================
# MAIN
# ===========================================================================
generate_wrappers
build_wars
deploy_to_compose_dirs
