#!/usr/bin/env bash
#
# war-deploy.sh — Build GridSuite microservices as WAR files for docker-compose.
#                 Zero modifications to original server source files.
#
# Word of Caution, the whole script with comments (except this sentence)
# has been generated by opus4.6 without much look at the details.
#
# Usage:
#   ./war-deploy.sh [OPTIONS]
#
# Options:
#   --only SRV         Only process this server (repeatable)
#   --help             Show this help
#
# Strategy ("wrapper POM" approach):
#   Instead of modifying original Spring Boot server sources to produce WAR files,
#   we generate lightweight wrapper Maven projects that:
#   1. Depend on the original server's classes JAR (available because powsybl-parent-ws
#      configures spring-boot-maven-plugin with <classifier>exec</classifier>, so
#      `mvn install` installs both the executable fat JAR and a plain classes JAR)
#   2. Provide a SpringBootServletInitializer subclass (required for WAR deployment)
#   3. Set spring.config.additional-location for per-WAR config overrides
#   4. Package as WAR with <finalName> = desired context path
#
#   This keeps all server submodules UNMODIFIED while producing deployable WARs.
#
#   Shared classloading: all deps (highest version across servers) are placed
#   in Tomcat's lib/ via gen/shared-lib/. WARs use packagingIncludes to keep
#   only the server's own classes JAR. No per-WAR version overrides — all
#   servers use the same shared version to avoid ServiceLoader/SPI classloader
#   conflicts.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGGREGATOR_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
SERVERS_DIR="$AGGREGATOR_ROOT/backend/servers"
SERVERS_REACTOR_DIR="$SCRIPT_DIR/gen/servers-reactor"
SHARED_DEPS_DIR="$SCRIPT_DIR/gen/shared-deps"
WRAPPERS_DIR="$SCRIPT_DIR/gen/war-wrappers"
WEBAPPS_DIR="$SCRIPT_DIR/gen/wars"
CONFIG_DIR="$SCRIPT_DIR/gen/externalized-war-configs"
SHARED_LIB_DIR="$SCRIPT_DIR/gen/shared-lib"

# Base URL used inside docker network (container-to-container)
TOMCAT_BASE_URL="http://tomcat:8080"

# Defaults
ONLY_SERVERS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --only)         ONLY_SERVERS+=("$2"); shift 2 ;;
        --help)         sed -n '2,/^$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

log() { echo -e "\033[1;34m[WAR]\033[0m $*"; }
err() { echo -e "\033[1;31m[ERR]\033[0m $*" >&2; }

# ===========================================================================
# SERVER MANIFEST
# Format: context_name|server_folder|pom_subpath|app_class_fqn
#
# context_name: WAR filename / Tomcat context path
# server_folder: folder under backend/servers/
# pom_subpath: submodule path within server_folder (empty = root)
# app_class_fqn: fully qualified Application class name
# Lines starting with # are disabled. Uncomment to include in the build.
# ===========================================================================
MANIFEST=(
"actions-server|actions-server||org.gridsuite.actions.server.ActionsApplication"
#"balances-adjustment-server|balances-adjustment-server||org.gridsuite.balances.adjustment.server.BalancesAdjustmentApplication"
#"case-import-server|case-import-server||org.gridsuite.caseimport.server.CaseImportApplication"
#"case-validation-server|case-validation-server||org.gridsuite.casevalidation.server.CaseValidationApplication"
#"cgmes-boundary-server|cgmes-boundary-server||org.gridsuite.cgmes.boundary.server.CgmesBoundaryApplication"
#"cgmes-gl-server|cgmes-gl-server||org.gridsuite.cgmes.gl.server.CgmesGlApplication"
"directory-server|directory-server||org.gridsuite.directory.server.DirectoryApplication"
#"dynamic-mapping-server|dynamic-mapping-server||org.gridsuite.mapping.server.MappingApplication"
#"dynamic-margin-calculation-server|dynamic-margin-calculation-server||org.gridsuite.dynamicmargincalculation.server.DynamicMarginCalculationApplication"
#"dynamic-security-analysis-server|dynamic-security-analysis-server||org.gridsuite.dynamicsecurityanalysis.server.DynamicSecurityAnalysisApplication"
#"dynamic-simulation-server|dynamic-simulation-server||org.gridsuite.ds.server.DynamicSimulationApplication"
"explore-server|explore-server||org.gridsuite.explore.server.ExploreApplication"
"filter-server|filter-server||org.gridsuite.filter.server.FilterApplication"
"geo-data-server|geo-data-server||org.gridsuite.geodata.server.GeoDataApplication"
"loadflow-server|loadflow-server||org.gridsuite.loadflow.server.LoadFlowApplication"
#"merge-orchestrator-server|merge-orchestrator-server||org.gridsuite.merge.orchestrator.server.MergeOrchestratorApplication"
"network-map-server|network-map-server||org.gridsuite.network.map.NetworkMapApplication"
"network-modification-server|network-modification-server||org.gridsuite.modification.server.NetworkModificationApplication"
"network-store-server|powsybl-network-store-server|network-store-server|com.powsybl.network.store.server.NetworkStoreApplication"
#"odre-server|odre-server||org.gridsuite.odre.server.OdreApplication"
"case-server|powsybl-case-server||com.powsybl.caseserver.CaseApplication"
"network-conversion-server|powsybl-network-conversion-server||com.powsybl.network.conversion.server.NetworkConversionApplication"
"single-line-diagram-server|powsybl-single-line-diagram-server||com.powsybl.sld.server.SingleLineDiagramApplication"
"report-server|report-server||org.gridsuite.report.server.ReportApplication"
"security-analysis-server|security-analysis-server||org.gridsuite.securityanalysis.server.SecurityAnalysisApplication"
"sensitivity-analysis-server|sensitivity-analysis-server||org.gridsuite.sensitivityanalysis.server.SensitivityAnalysisApplication"
"shortcircuit-server|shortcircuit-server||org.gridsuite.shortcircuit.server.ShortCircuitApplication"
"study-config-server|study-config-server||org.gridsuite.studyconfig.server.StudyConfigApplication"
"study-server|study-server||org.gridsuite.study.server.StudyApplication"
#"timeseries-server|timeseries-server||org.gridsuite.timeseries.server.TimeSeriesApplication"
"user-admin-server|user-admin-server||org.gridsuite.useradmin.server.UserAdminApplication"
"user-identity-server|user-identity-oidc-replication-server||org.gridsuite.useridentity.oidcreplication.server.UserIdentityOidcReplicationApplication"
"voltage-init-server|voltage-init-server||org.gridsuite.voltageinit.server.VoltageInitApplication"
)

# Filter out commented entries (lines starting with #)
_filtered=()
for _e in "${MANIFEST[@]}"; do
    [[ "$_e" =~ ^# ]] || _filtered+=("$_e")
done
MANIFEST=("${_filtered[@]}")
unset _filtered _e

should_process() {
    local ctx="$1"
    if [[ ${#ONLY_SERVERS[@]} -gt 0 ]]; then
        for s in "${ONLY_SERVERS[@]}"; do
            [[ "$s" == "$ctx" ]] && return 0
        done
        return 1
    fi
    return 0
}

# Resolve a service key to its base-uri.
# Trailing slash is required: clients use UriComponentsBuilder.fromUriString(baseUri)
# which concatenates paths like "v1/networks/..." directly after the base URI.
# Without trailing slash: "http://tomcat:8080/network-store-serverv1/..." (broken)
# With trailing slash:    "http://tomcat:8080/network-store-server/v1/..." (correct)
resolve_base_uri() {
    local svc_key="$1"
    echo "${TOMCAT_BASE_URL}/${svc_key}/"
}

# Generate per-WAR config override with base-uri values pointing to Tomcat.
# Since we disable the "local" profile, we only need base-uri overrides in application.yml.
# Reads the original application-local file to discover which services are referenced,
# then generates a clean application.yml with only the base-uri section.
generate_local_config_override() {
    local ctx="$1"
    local server_folder="$2"
    local pom_subpath="$3"
    local wrapper_dir="$4"

    local module_dir="$SERVERS_DIR/$server_folder"
    [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

    # Find the original application-local file to discover service references
    local orig_file=""
    for ext in yaml yml; do
        if [[ -f "$module_dir/src/main/resources/application-local.$ext" ]]; then
            orig_file="$module_dir/src/main/resources/application-local.$ext"
            break
        fi
    done
    [[ -z "$orig_file" ]] && return 0

    # Detect which format gridsuite: services: uses (list-style vs map-style)
    local uses_list_style=false
    if grep -qE '^\s+-\s*(name:|$)' "$orig_file" 2>/dev/null; then
        uses_list_style=true
    fi

    # Extract service keys referenced in the file
    local powsybl_services=() gridsuite_services=()
    local current_section=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^powsybl: ]]; then
            current_section="powsybl"
        elif [[ "$line" =~ ^gridsuite: ]]; then
            current_section="gridsuite"
        elif [[ ! "$line" =~ ^[[:space:]] && ! "$line" =~ ^# && -n "$line" ]]; then
            current_section="other"
        fi

        # Map-style key: "    server-name:"
        if [[ "$line" =~ ^[[:space:]]{4}([a-z][a-z0-9-]+):$ ]]; then
            local key="${BASH_REMATCH[1]}"
            if [[ "$current_section" == "powsybl" ]]; then
                powsybl_services+=("$key")
            elif [[ "$current_section" == "gridsuite" ]]; then
                gridsuite_services+=("$key")
            fi
        fi
        # List-style: "- name: xxx" or "    name: xxx"
        if [[ "$line" =~ ^[[:space:]]+-[[:space:]]*name:[[:space:]]*(.+) ]]; then
            local key="${BASH_REMATCH[1]}"
            key="${key%%[[:space:]]}"
            [[ "$current_section" == "gridsuite" ]] && gridsuite_services+=("$key")
        elif [[ "$line" =~ ^[[:space:]]+name:[[:space:]]*(.+) && "$current_section" == "gridsuite" ]]; then
            local key="${BASH_REMATCH[1]}"
            key="${key%%[[:space:]]}"
            gridsuite_services+=("$key")
        fi
    done < "$orig_file"

    # If no services referenced, no config needed
    if [[ ${#powsybl_services[@]} -eq 0 && ${#gridsuite_services[@]} -eq 0 ]]; then
        return 0
    fi

    local out_file="$CONFIG_DIR/$ctx/application.yml"
    mkdir -p "$CONFIG_DIR/$ctx"

    local output=""

    # Generate powsybl: services: section (always map-style)
    if [[ ${#powsybl_services[@]} -gt 0 ]]; then
        output+="powsybl:"$'\n'
        output+="  services:"$'\n'
        for svc in "${powsybl_services[@]}"; do
            local uri
            uri=$(resolve_base_uri "$svc")
            output+="    ${svc}:"$'\n'
            output+="      base-uri: ${uri}"$'\n'
        done
    fi

    # Generate gridsuite: services: section
    if [[ ${#gridsuite_services[@]} -gt 0 ]]; then
        [[ -n "$output" ]] && output+=$'\n'
        output+="gridsuite:"$'\n'
        output+="  services:"$'\n'
        if $uses_list_style; then
            for svc in "${gridsuite_services[@]}"; do
                local uri
                uri=$(resolve_base_uri "$svc")
                output+="    -"$'\n'
                output+="      name: ${svc}"$'\n'
                output+="      base-uri: ${uri}"$'\n'
            done
        else
            for svc in "${gridsuite_services[@]}"; do
                local uri
                uri=$(resolve_base_uri "$svc")
                output+="    ${svc}:"$'\n'
                output+="      base-uri: ${uri}"$'\n'
            done
        fi
    fi

    echo -n "$output" > "$out_file"
}

# ---------------------------------------------------------------------------
# Add auto-configuration exclusions for servers affected by shared-lib.
# With shared-lib, ALL Spring Boot auto-configuration trigger classes are on
# the common classpath, so auto-configs activate for ALL webapps — even servers
# that don't use a given feature. This function detects which features each
# server actually uses and adds exclusions for the rest.
# ---------------------------------------------------------------------------
add_shared_lib_autoconfig_exclusions() {
    local datasource_exclusions=(
        "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
        "org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration"
        "org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration"
        "org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration"
    )
    local security_exclusions=(
        "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"
        "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"
        "org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration"
    )

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local deps_file="${DEPS_DIR}/${ctx}.parsed"
        [[ -f "$deps_file" ]] || continue

        local needs_exclusions=false
        local exclusions_to_add=()

        # Check if server uses a database
        if ! grep -q 'spring-boot-starter-data-jpa\|spring-data-r2dbc\|spring-boot-starter-jdbc\|liquibase' "$deps_file"; then
            needs_exclusions=true
            exclusions_to_add+=("${datasource_exclusions[@]}")
        fi

        # Check if server uses Spring Security
        if ! grep -q 'spring-boot-starter-security\|spring-security-config' "$deps_file"; then
            needs_exclusions=true
            exclusions_to_add+=("${security_exclusions[@]}")
        fi

        $needs_exclusions || continue

        local module_dir="$SERVERS_DIR/$server_folder"
        [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

        # Find the server's config/application.yaml from source to extract existing exclusions
        local config_yaml="$module_dir/src/main/resources/config/application.yaml"
        [[ ! -f "$config_yaml" ]] && config_yaml="$module_dir/src/main/resources/config/application.yml"

        # Collect existing exclusions from the server's config/application.yaml
        local all_exclusions=()
        if [[ -f "$config_yaml" ]]; then
            while IFS= read -r line; do
                local cls
                cls=$(echo "$line" | sed -n 's/^[[:space:]]*-[[:space:]]*//p')
                [[ -n "$cls" ]] && all_exclusions+=("$cls")
            done < <(sed -n '/autoconfigure:/,/^[^ ]/p' "$config_yaml" | \
                     sed -n '/exclude:/,/^[[:space:]]*[^-[:space:]]/p' | \
                     grep '^[[:space:]]*-')
        fi

        # Add new exclusions (dedup)
        for excl in "${exclusions_to_add[@]}"; do
            local found=false
            for existing in "${all_exclusions[@]}"; do
                [[ "$existing" == "$excl" ]] && found=true && break
            done
            $found || all_exclusions+=("$excl")
        done

        # Write/update externalized config
        local out_file="$CONFIG_DIR/$ctx/application.yml"
        mkdir -p "$CONFIG_DIR/$ctx"

        # Build the exclusion YAML block
        local excl_yaml="spring:"$'\n'"  autoconfigure:"$'\n'"    exclude:"$'\n'
        for excl in "${all_exclusions[@]}"; do
            excl_yaml+="    - ${excl}"$'\n'
        done

        if [[ -f "$out_file" ]]; then
            # Prepend to existing config (spring: block must come first)
            local existing
            existing=$(cat "$out_file")
            echo -n "${excl_yaml}
${existing}" > "$out_file"
        else
            echo -n "$excl_yaml" > "$out_file"
        fi

        log "  $ctx: added ${#exclusions_to_add[@]} auto-config exclusions"
    done
}

# ===========================================================================
# PHASE 0: FIND COMMON DEPENDENCIES ACROSS ALL SERVERS
# Generates a "servers-reactor" POM that references all original server modules,
# then runs a SINGLE `mvn dependency:list` on that reactor. Each module writes
# its resolved deps to its own target/deps.txt. For each groupId:artifactId,
# the most common version is selected. A "shared-deps" POM is generated with
# all these as compile deps (used later by dependency:copy-dependencies to
# populate Tomcat's lib/). Per-server version overrides are recorded for
# use in packagingExcludes negations.
# ===========================================================================
find_common_deps() {
    log "=== Generating servers-reactor POM ==="
    rm -rf "$SERVERS_REACTOR_DIR"
    mkdir -p "$SERVERS_REACTOR_DIR"

    # Build the <modules> list pointing to original server sources
    local server_modules=""
    local server_count=0
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local rel_path="../../../../../../backend/servers/$server_folder"
        [[ -n "$pom_subpath" ]] && rel_path="$rel_path/$pom_subpath"
        server_modules+="        <module>${rel_path}</module>\n"
        server_count=$((server_count + 1))
    done

    cat > "$SERVERS_REACTOR_DIR/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gridsuite.war</groupId>
    <artifactId>servers-reactor</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
$(echo -e "$server_modules")    </modules>
</project>
POM

    # Single Maven invocation: resolve deps for all server modules at once.
    # Each module writes target/deps.txt relative to its own basedir.
    log "=== Resolving dependencies ($server_count servers, single mvn invocation) ==="
    (cd "$SERVERS_REACTOR_DIR" && mvn dependency:list \
        -DincludeScope=runtime \
        -DoutputAbsoluteArtifactFilename=false \
        -DoutputFile=target/deps.txt \
        -q) || {
        err "Failed to resolve dependencies"
        return 1
    }

    # Parse each module's target/deps.txt
    log "=== Analyzing dependencies across $server_count servers ==="
    local deps_dir="$SCRIPT_DIR/gen/deps"
    rm -rf "$deps_dir"
    mkdir -p "$deps_dir"

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local module_dir="$SERVERS_DIR/$server_folder"
        [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"
        local deps_file="$module_dir/target/deps.txt"

        if [[ ! -f "$deps_file" ]]; then
            err "  No deps.txt for $ctx"
            continue
        fi

        # Parse: extract groupId:artifactId:type:classifier:version
        # dependency:list format is g:a:t:v:scope (5 fields) or g:a:t:classifier:v:scope (6 fields)
        # Normalize to g:a:type:classifier:version (classifier empty if none)
        grep -oP '^\s+\S+' "$deps_file" | sed 's/^[[:space:]]*//' | \
            awk -F: 'NF==5 {print $1":"$2":"$3"::"$4} NF>=6 {print $1":"$2":"$3":"$4":"$5}' | \
            sort -u > "$deps_dir/${ctx}.parsed"
    done

    # For each groupId:artifactId:type:classifier, find the most common version.
    log "=== Selecting most common version per artifact ==="

    # Collect all deps, count each full coordinate (with version)
    cat "$deps_dir"/*.parsed | sort | uniq -c | sort -rn > "$deps_dir/_full_counts.txt"

    # For each g:a:t:classifier key, pick the HIGHEST version.
    # Using the highest version avoids ServiceLoader/SPI classloader conflicts
    # that occur when a WAR overrides a shared-lib JAR with a different version.
    # Output: g:a:type:classifier:version (the "winning" version for shared-lib)
    awk '{$1=$1; count=$1; $1=""; sub(/^ /,""); print $0}' "$deps_dir/_full_counts.txt" | \
        sort -t: -k1,4 -k5Vr | \
        awk -F: '{key=$1":"$2":"$3":"$4} !seen[key]++ {print}' | \
        grep ':jar:' | \
        grep -v 'javax\.servlet\|jakarta\.servlet\|tomcat-embed\|spring-boot-starter-tomcat\|org\.antlr:antlr4:' \
        > "$deps_dir/_shared.txt" || true

    local shared_count
    shared_count=$(wc -l < "$deps_dir/_shared.txt")
    log "  $shared_count artifacts selected for shared-lib (highest version each)"

    # Build a lookup file: key -> version (for detecting per-server overrides)
    awk -F: '{print $1":"$2":"$3":"$4"="$5}' "$deps_dir/_shared.txt" > "$deps_dir/_shared_lookup.txt"

    # Note: no per-server version overrides. With shared classloading, all servers
    # must use the same version from shared-lib. Version overrides (keeping a
    # different version in WEB-INF/lib) cause ServiceLoader/SPI classloader conflicts
    # because the interface from the parent classloader != the interface from the
    # child classloader.

    # Generate shared-deps POM: lists all common deps as compile dependencies.
    # Used by dependency:copy-dependencies to populate Tomcat's lib/.
    log "=== Generating shared-deps POM ==="
    rm -rf "$SHARED_DEPS_DIR"
    mkdir -p "$SHARED_DEPS_DIR"

    # Since _shared.txt is already the full transitive closure from the servers,
    # exclude all transitives to avoid pulling in artifacts not in Maven Central
    # (e.g. com.bea.xml:jsr173-ri via stax-utils).
    local shared_deps_xml=""
    while IFS=: read -r g a t classifier v; do
        shared_deps_xml+="
        <dependency>
            <groupId>${g}</groupId>
            <artifactId>${a}</artifactId>
            <version>${v}</version>"
        if [[ -n "$classifier" ]]; then
            shared_deps_xml+="
            <classifier>${classifier}</classifier>"
        fi
        shared_deps_xml+="
            <exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions>
        </dependency>"
    done < "$deps_dir/_shared.txt"

    cat > "$SHARED_DEPS_DIR/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gridsuite.war</groupId>
    <artifactId>shared-deps</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <description>All shared dependencies (most common version). Used to collect JARs for Tomcat lib/.</description>

    <dependencies>${shared_deps_xml}
    </dependencies>
</project>
POM

    # Export for use by generate_wrappers
    SHARED_DEPS_FILE="$deps_dir/_shared.txt"
    DEPS_DIR="$deps_dir"
}

# ===========================================================================
# PHASE 1: GENERATE WRAPPER PROJECTS
# ===========================================================================
generate_wrappers() {
    log "=== Generating wrapper projects ==="
    rm -rf "$WRAPPERS_DIR"
    mkdir -p "$WRAPPERS_DIR"

    local modules=""

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local module_dir="$SERVERS_DIR/$server_folder"
        [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

        # Get groupId, artifactId, version from the server's pom
        local group_id artifact_id version parent_group parent_version

        parent_group=$(sed -n '/<parent>/,/<\/parent>/p' "$module_dir/pom.xml" | grep '<groupId>' | sed 's/.*<groupId>//;s/<.*//' | tr -d ' ')
        parent_version=$(sed -n '/<parent>/,/<\/parent>/p' "$module_dir/pom.xml" | grep '<version>' | sed 's/.*<version>//;s/<.*//' | tr -d ' ')
        artifact_id=$(sed -n '/<\/parent>/,$ p' "$module_dir/pom.xml" | grep -m1 '<artifactId>' | sed 's/.*<artifactId>//;s/<.*//' | tr -d ' ')
        version=$(sed -n '/<\/parent>/,/<\(build\|dependencies\|dependencyManagement\|properties\)>/ p' "$module_dir/pom.xml" | grep -m1 '<version>' | sed 's/.*<version>//;s/<.*//' | tr -d ' ' || true)
        group_id=$(sed -n '/<\/parent>/,/<\(build\|dependencies\|dependencyManagement\|properties\)>/ p' "$module_dir/pom.xml" | grep -m1 '<groupId>' | sed 's/.*<groupId>//;s/<.*//' | tr -d ' ' || true)

        # Fall back to parent values if not specified at project level
        [[ -z "$group_id" ]] && group_id="$parent_group"
        [[ -z "$version" ]] && version="$parent_version"

        # Detect spring-boot version from this server's resolved deps
        local spring_boot_version
        spring_boot_version=$(grep 'org\.springframework\.boot:spring-boot:jar:' \
            "${DEPS_DIR}/${ctx}.parsed" | awk -F: '{print $5}' | head -1)
        [[ -z "$spring_boot_version" ]] && spring_boot_version="3.5.11"

        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        mkdir -p "$wrapper_dir/src/main/java/org/gridsuite/war"

        # Generate WarInitializer.java
        local simple_class="${app_class##*.}"
        local initializer_class="${simple_class/Application/WarInitializer}"
        cat > "$wrapper_dir/src/main/java/org/gridsuite/war/${initializer_class}.java" << JAVA
package org.gridsuite.war;

import ${app_class};
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ${initializer_class} extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(${simple_class}.class)
            .properties("spring.config.additional-location=optional:file:/config/${ctx}/");
    }
}
JAVA

        # Build packagingIncludes: only keep the server's own classes JAR.
        # Everything else (shared deps) is excluded from the WAR.
        # Non-JAR content (WEB-INF/classes, META-INF) is always included.
        local server_jar_name="${artifact_id}-${version}.jar"
        local packaging_includes="META-INF/**,WEB-INF/classes/**,WEB-INF/lib/${server_jar_name}"

        cat > "$wrapper_dir/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.gridsuite.war</groupId>
        <artifactId>war-wrappers</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>${ctx}-war</artifactId>
    <packaging>war</packaging>

    <dependencies>
        <dependency>
            <groupId>${group_id}</groupId>
            <artifactId>${artifact_id}</artifactId>
            <version>${version}</version>
        </dependency>
        <!-- Compile dependency on spring-boot: needed to compile the WarInitializer
             class (extends SpringBootServletInitializer). Version matched from this
             server's resolved dependency tree. -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <version>${spring_boot_version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${ctx}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <packagingIncludes>${packaging_includes}</packagingIncludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
POM

        modules="$modules        <module>$ctx</module>\n"
        log "  ${ctx}-war -> $module_dir"
    done

    # Generate reactor parent pom (minimal: just modules + compiler settings)
    cat > "$WRAPPERS_DIR/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gridsuite.war</groupId>
    <artifactId>war-wrappers</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <modules>
        <!-- Server sources (builds classes JARs needed by wrappers) -->
        <module>../servers-reactor</module>
        <!-- WAR wrappers -->
$(echo -e "$modules")    </modules>
</project>
POM

    # Generate per-WAR config overrides directly into gen/externalized-war-configs/
    rm -rf "$CONFIG_DIR"
    log "=== Generating externalized WAR additional-configs ==="
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue
        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        generate_local_config_override "$ctx" "$server_folder" "$pom_subpath" "$wrapper_dir"
    done
    add_shared_lib_autoconfig_exclusions
    (cd "$SCRIPT_DIR" && find gen/externalized-war-configs -type f 2>/dev/null) || true
}

# ===========================================================================
# PHASE 2: BUILD ALL (SINGLE REACTOR)
# war-wrappers/pom.xml includes servers-reactor as a module, so a single
# `mvn package` builds server JARs first (reactor ordering), then WAR wrappers.
# ===========================================================================
build_wars() {
    # Prefer mvnd (Maven Daemon) for faster builds; fall back to mvn -q
    local mvn_cmd
    if command -v mvnd &>/dev/null; then
        mvn_cmd="mvnd"
        log "=== Building with mvnd ==="
    else
        mvn_cmd="mvn -T4 -q"
        log "=== Building with mvn (mvnd not found, using -T4 -q) ==="
    fi

    log "  Running: $mvn_cmd package -DskipTests -f $WRAPPERS_DIR/pom.xml"
    (cd "$WRAPPERS_DIR" && $mvn_cmd package -DskipTests) || {
        err "Reactor build failed"
        return 1
    }

    # Verify
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue
        if [[ ! -f "$WRAPPERS_DIR/$ctx/target/${ctx}.war" ]]; then
            err "Missing: $WRAPPERS_DIR/$ctx/target/${ctx}.war"
        fi
    done
}

# ===========================================================================
# PHASE 3: COPY WARS TO DOCKER-COMPOSE MOUNT DIR
# ===========================================================================
deploy_to_compose_dirs() {
    log "=== Copying WARs to gen/wars/ ==="
    rm -f "$WEBAPPS_DIR"/*.war 2>/dev/null || true
    mkdir -p "$WEBAPPS_DIR"

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local war="$WRAPPERS_DIR/$ctx/target/${ctx}.war"
        if [[ -f "$war" ]]; then
            cp "$war" "$WEBAPPS_DIR/"
        else
            err "Missing: $war"
        fi
    done

    (cd "$SCRIPT_DIR" && find gen/wars -maxdepth 1 -name '*.war' -type f 2>/dev/null) || true
    echo ""
    echo "Folders gen/wars/, gen/externalized-war-configs/ and gen/shared-lib/ ready for \$ docker compose up"
}

# ===========================================================================
# PHASE 4: COLLECT SHARED JARS FOR TOMCAT LIB
# Uses dependency:copy-dependencies on the shared-deps POM to download all
# common JARs into gen/shared-lib/. These are the JARs excluded from WARs
# by packagingExcludes and must be in Tomcat's classpath.
# ===========================================================================
collect_shared_libs() {
    log "=== Collecting shared JARs to gen/shared-lib/ ==="
    rm -rf "$SHARED_LIB_DIR"
    mkdir -p "$SHARED_LIB_DIR"

    (cd "$SHARED_DEPS_DIR" && mvn dependency:copy-dependencies \
        -DoutputDirectory="$SHARED_LIB_DIR" \
        -q) || {
        err "Failed to collect shared JARs"
        return 1
    }

    # Extract resource bundles (.properties) from each server's classes JAR
    # and package them into a single resource-bundles.jar in shared-lib.
    # This is needed because MultiBundleMessageTemplateProvider (in powsybl-commons,
    # loaded by the common classloader) calls ResourceBundle.getBundle() without
    # specifying a classloader, so it uses the caller's CL (common CL) which
    # can't see .properties files inside each WAR's WEB-INF/lib/ server JAR.
    local bundle_tmp="$SCRIPT_DIR/gen/_resource-bundles"
    rm -rf "$bundle_tmp"
    mkdir -p "$bundle_tmp"
    local found_bundles=false

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local server_dir="$SERVERS_DIR/$server_folder"
        # Find reports*.properties in the server source
        local res_dir="$server_dir/src/main/resources"
        if [[ -d "$res_dir" ]]; then
            while IFS= read -r propfile; do
                local rel="${propfile#$res_dir/}"
                mkdir -p "$bundle_tmp/$(dirname "$rel")"
                cp "$propfile" "$bundle_tmp/$rel"
                found_bundles=true
            done < <(find "$res_dir" -name 'reports*.properties' -type f 2>/dev/null)
        fi
    done

    if [[ "$found_bundles" == "true" ]]; then
        (cd "$bundle_tmp" && jar cf "$SHARED_LIB_DIR/resource-bundles.jar" .)
        local bundle_count
        bundle_count=$(find "$bundle_tmp" -name '*.properties' -type f | wc -l)
        log "  Packaged $bundle_count resource bundle files into resource-bundles.jar"
    fi
    rm -rf "$bundle_tmp"

    local count
    count=$(find "$SHARED_LIB_DIR" -name '*.jar' -type f | wc -l)
    log "  $count JARs collected in gen/shared-lib/"
}

# ===========================================================================
# MAIN
# ===========================================================================
find_common_deps
generate_wrappers
build_wars
collect_shared_libs
deploy_to_compose_dirs
