#!/usr/bin/env bash
#
# war-deploy.sh — Build GridSuite microservices as WAR files for docker-compose.
#                 Zero modifications to original server source files.
#
# Word of Caution, the whole script with comments (except this sentence)
# has been generated by opus4.6 without much look at the details.
#
# Usage:
#   ./war-deploy.sh [OPTIONS]
#
# Options:
#   --only SRV         Only process this server (repeatable)
#   --help             Show this help
#
# Strategy ("wrapper POM" approach):
#   Instead of modifying original Spring Boot server sources to produce WAR files,
#   we generate lightweight wrapper Maven projects that:
#   1. Depend on the original server's classes JAR (available because powsybl-parent-ws
#      configures spring-boot-maven-plugin with <classifier>exec</classifier>, so
#      `mvn install` installs both the executable fat JAR and a plain classes JAR)
#   2. Provide a SpringBootServletInitializer subclass (required for WAR deployment)
#   3. Set spring.config.additional-location for per-WAR config overrides
#   4. Package as WAR with <finalName> = desired context path
#
#   This keeps all server submodules UNMODIFIED while producing deployable WARs.
#
# Future improvements:
#   - Move shared JARs (Spring, Hibernate, powsybl-commons, etc.) into Tomcat's
#     lib/ directory so they are loaded once by the common classloader. This would
#     significantly reduce Metaspace usage (each WAR currently loads its own copy
#     of every dependency class).
#   - Reduce duplication in config override generation: many servers share the same
#     service references (e.g. network-store, report-server). A template or merge
#     system could replace per-server YAML generation.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGGREGATOR_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
SERVERS_DIR="$AGGREGATOR_ROOT/backend/servers"
WRAPPERS_DIR="$SCRIPT_DIR/gen/war-wrappers"
WEBAPPS_DIR="$SCRIPT_DIR/gen/wars"
CONFIG_DIR="$SCRIPT_DIR/gen/externalized-war-configs"

# Base URL used inside docker network (container-to-container)
TOMCAT_BASE_URL="http://tomcat:8080"

# Defaults
ONLY_SERVERS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --only)         ONLY_SERVERS+=("$2"); shift 2 ;;
        --help)         sed -n '2,/^$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

log() { echo -e "\033[1;34m[WAR]\033[0m $*"; }
err() { echo -e "\033[1;31m[ERR]\033[0m $*" >&2; }

# ===========================================================================
# SERVER MANIFEST
# Format: context_name|server_folder|pom_subpath|app_class_fqn
#
# context_name: WAR filename / Tomcat context path
# server_folder: folder under backend/servers/
# pom_subpath: submodule path within server_folder (empty = root)
# app_class_fqn: fully qualified Application class name
# Lines starting with # are disabled. Uncomment to include in the build.
# ===========================================================================
MANIFEST=(
"actions-server|actions-server||org.gridsuite.actions.server.ActionsApplication"
#"balances-adjustment-server|balances-adjustment-server||org.gridsuite.balances.adjustment.server.BalancesAdjustmentApplication"
#"case-import-server|case-import-server||org.gridsuite.caseimport.server.CaseImportApplication"
#"case-validation-server|case-validation-server||org.gridsuite.casevalidation.server.CaseValidationApplication"
#"cgmes-boundary-server|cgmes-boundary-server||org.gridsuite.cgmes.boundary.server.CgmesBoundaryApplication"
#"cgmes-gl-server|cgmes-gl-server||org.gridsuite.cgmes.gl.server.CgmesGlApplication"
"directory-server|directory-server||org.gridsuite.directory.server.DirectoryApplication"
#"dynamic-mapping-server|dynamic-mapping-server||org.gridsuite.mapping.server.MappingApplication"
#"dynamic-margin-calculation-server|dynamic-margin-calculation-server||org.gridsuite.dynamicmargincalculation.server.DynamicMarginCalculationApplication"
#"dynamic-security-analysis-server|dynamic-security-analysis-server||org.gridsuite.dynamicsecurityanalysis.server.DynamicSecurityAnalysisApplication"
#"dynamic-simulation-server|dynamic-simulation-server||org.gridsuite.ds.server.DynamicSimulationApplication"
"explore-server|explore-server||org.gridsuite.explore.server.ExploreApplication"
"filter-server|filter-server||org.gridsuite.filter.server.FilterApplication"
"geo-data-server|geo-data-server||org.gridsuite.geodata.server.GeoDataApplication"
"loadflow-server|loadflow-server||org.gridsuite.loadflow.server.LoadFlowApplication"
#"merge-orchestrator-server|merge-orchestrator-server||org.gridsuite.merge.orchestrator.server.MergeOrchestratorApplication"
"network-map-server|network-map-server||org.gridsuite.network.map.NetworkMapApplication"
"network-modification-server|network-modification-server||org.gridsuite.modification.server.NetworkModificationApplication"
"network-store-server|powsybl-network-store-server|network-store-server|com.powsybl.network.store.server.NetworkStoreApplication"
#"odre-server|odre-server||org.gridsuite.odre.server.OdreApplication"
"case-server|powsybl-case-server||com.powsybl.caseserver.CaseApplication"
"network-conversion-server|powsybl-network-conversion-server||com.powsybl.network.conversion.server.NetworkConversionApplication"
"single-line-diagram-server|powsybl-single-line-diagram-server||com.powsybl.sld.server.SingleLineDiagramApplication"
"report-server|report-server||org.gridsuite.report.server.ReportApplication"
"security-analysis-server|security-analysis-server||org.gridsuite.securityanalysis.server.SecurityAnalysisApplication"
"sensitivity-analysis-server|sensitivity-analysis-server||org.gridsuite.sensitivityanalysis.server.SensitivityAnalysisApplication"
"shortcircuit-server|shortcircuit-server||org.gridsuite.shortcircuit.server.ShortCircuitApplication"
"study-config-server|study-config-server||org.gridsuite.studyconfig.server.StudyConfigApplication"
"study-server|study-server||org.gridsuite.study.server.StudyApplication"
#"timeseries-server|timeseries-server||org.gridsuite.timeseries.server.TimeSeriesApplication"
"user-admin-server|user-admin-server||org.gridsuite.useradmin.server.UserAdminApplication"
"user-identity-server|user-identity-oidc-replication-server||org.gridsuite.useridentity.oidcreplication.server.UserIdentityOidcReplicationApplication"
"voltage-init-server|voltage-init-server||org.gridsuite.voltageinit.server.VoltageInitApplication"
)

# Filter out commented entries (lines starting with #)
_filtered=()
for _e in "${MANIFEST[@]}"; do
    [[ "$_e" =~ ^# ]] || _filtered+=("$_e")
done
MANIFEST=("${_filtered[@]}")
unset _filtered _e

# Per-server metadata cached by generate_wrappers() and reused by
# probe_and_patch_dependencies(), so the pom.xml can be regenerated a second
# time (with dependency corrections) without recomputing/re-parsing anything.
declare -A WRAP_MODULE_DIR WRAP_GROUP_ID WRAP_ARTIFACT_ID WRAP_VERSION WRAP_EXTRA_DEPS WRAP_EXCLUDE_GA

should_process() {
    local ctx="$1"
    if [[ ${#ONLY_SERVERS[@]} -gt 0 ]]; then
        for s in "${ONLY_SERVERS[@]}"; do
            [[ "$s" == "$ctx" ]] && return 0
        done
        return 1
    fi
    return 0
}

# Resolve a service key to its base-uri.
# Trailing slash is required: clients use UriComponentsBuilder.fromUriString(baseUri)
# which concatenates paths like "v1/networks/..." directly after the base URI.
# Without trailing slash: "http://tomcat:8080/network-store-serverv1/..." (broken)
# With trailing slash:    "http://tomcat:8080/network-store-server/v1/..." (correct)
resolve_base_uri() {
    local svc_key="$1"
    echo "${TOMCAT_BASE_URL}/${svc_key}/"
}

# Generate per-WAR config override with base-uri values pointing to Tomcat.
# Since we disable the "local" profile, we only need base-uri overrides in application.yml.
# Reads the original application-local file to discover which services are referenced,
# then generates a clean application.yml with only the base-uri section.
generate_local_config_override() {
    local ctx="$1"
    local server_folder="$2"
    local pom_subpath="$3"
    local wrapper_dir="$4"

    local module_dir="$SERVERS_DIR/$server_folder"
    [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

    # Find the original application-local file to discover service references
    local orig_file=""
    for ext in yaml yml; do
        if [[ -f "$module_dir/src/main/resources/application-local.$ext" ]]; then
            orig_file="$module_dir/src/main/resources/application-local.$ext"
            break
        fi
    done
    [[ -z "$orig_file" ]] && return 0

    # Detect which format gridsuite: services: uses (list-style vs map-style)
    local uses_list_style=false
    if grep -qE '^\s+-\s*(name:|$)' "$orig_file" 2>/dev/null; then
        uses_list_style=true
    fi

    # Extract service keys referenced in the file
    local powsybl_services=() gridsuite_services=()
    local current_section=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^powsybl: ]]; then
            current_section="powsybl"
        elif [[ "$line" =~ ^gridsuite: ]]; then
            current_section="gridsuite"
        elif [[ ! "$line" =~ ^[[:space:]] && ! "$line" =~ ^# && -n "$line" ]]; then
            current_section="other"
        fi

        # Map-style key: "    server-name:"
        if [[ "$line" =~ ^[[:space:]]{4}([a-z][a-z0-9-]+):$ ]]; then
            local key="${BASH_REMATCH[1]}"
            if [[ "$current_section" == "powsybl" ]]; then
                powsybl_services+=("$key")
            elif [[ "$current_section" == "gridsuite" ]]; then
                gridsuite_services+=("$key")
            fi
        fi
        # List-style: "- name: xxx" or "    name: xxx"
        if [[ "$line" =~ ^[[:space:]]+-[[:space:]]*name:[[:space:]]*(.+) ]]; then
            local key="${BASH_REMATCH[1]}"
            key="${key%%[[:space:]]}"
            [[ "$current_section" == "gridsuite" ]] && gridsuite_services+=("$key")
        elif [[ "$line" =~ ^[[:space:]]+name:[[:space:]]*(.+) && "$current_section" == "gridsuite" ]]; then
            local key="${BASH_REMATCH[1]}"
            key="${key%%[[:space:]]}"
            gridsuite_services+=("$key")
        fi
    done < "$orig_file"

    # If no services referenced, no config needed
    if [[ ${#powsybl_services[@]} -eq 0 && ${#gridsuite_services[@]} -eq 0 ]]; then
        return 0
    fi

    local out_file="$CONFIG_DIR/$ctx/application.yml"
    mkdir -p "$CONFIG_DIR/$ctx"

    local output=""

    # Generate powsybl: services: section (always map-style)
    if [[ ${#powsybl_services[@]} -gt 0 ]]; then
        output+="powsybl:"$'\n'
        output+="  services:"$'\n'
        for svc in "${powsybl_services[@]}"; do
            local uri
            uri=$(resolve_base_uri "$svc")
            output+="    ${svc}:"$'\n'
            output+="      base-uri: ${uri}"$'\n'
        done
    fi

    # Generate gridsuite: services: section
    if [[ ${#gridsuite_services[@]} -gt 0 ]]; then
        [[ -n "$output" ]] && output+=$'\n'
        output+="gridsuite:"$'\n'
        output+="  services:"$'\n'
        if $uses_list_style; then
            for svc in "${gridsuite_services[@]}"; do
                local uri
                uri=$(resolve_base_uri "$svc")
                output+="    -"$'\n'
                output+="      name: ${svc}"$'\n'
                output+="      base-uri: ${uri}"$'\n'
            done
        else
            for svc in "${gridsuite_services[@]}"; do
                local uri
                uri=$(resolve_base_uri "$svc")
                output+="    ${svc}:"$'\n'
                output+="      base-uri: ${uri}"$'\n'
            done
        fi
    fi

    echo -n "$output" > "$out_file"
}

# Writes a wrapper's pom.xml from the shared template. Called twice per server:
# once by generate_wrappers() with extra_managed_deps="" (baseline), and again by
# probe_and_patch_dependencies() with the corrections found by diffing the server's
# and the baseline wrapper's `mvn dependency:list` output.
write_wrapper_pom() {
    local wrapper_dir="$1" ctx="$2" group_id="$3" artifact_id="$4" version="$5" extra_deps="$6" extra_managed_deps="$7"
    cat > "$wrapper_dir/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.gridsuite.war</groupId>
        <artifactId>war-wrappers</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>${ctx}-war</artifactId>
    <packaging>war</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${group_id}</groupId>
                <artifactId>${artifact_id}</artifactId>
                <version>${version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>${extra_managed_deps}
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${group_id}</groupId>
            <artifactId>${artifact_id}</artifactId>
            <version>${version}</version>
        </dependency>${extra_deps}
    </dependencies>

    <build>
        <finalName>${ctx}</finalName>
    </build>
</project>
POM
}

# ===========================================================================
# PHASE 1: GENERATE WRAPPER PROJECTS
# ===========================================================================
generate_wrappers() {
    log "=== Generating wrapper projects ==="
    rm -rf "$WRAPPERS_DIR"
    mkdir -p "$WRAPPERS_DIR"

    local modules=""

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local module_dir="$SERVERS_DIR/$server_folder"
        [[ -n "$pom_subpath" ]] && module_dir="$module_dir/$pom_subpath"

        # Get groupId, artifactId, version from the server's pom
        local group_id artifact_id version parent_group parent_version

        parent_group=$(sed -n '/<parent>/,/<\/parent>/p' "$module_dir/pom.xml" | grep '<groupId>' | sed 's/.*<groupId>//;s/<.*//' | tr -d ' ')
        parent_version=$(sed -n '/<parent>/,/<\/parent>/p' "$module_dir/pom.xml" | grep '<version>' | sed 's/.*<version>//;s/<.*//' | tr -d ' ')
        artifact_id=$(sed -n '/<\/parent>/,$ p' "$module_dir/pom.xml" | grep -m1 '<artifactId>' | sed 's/.*<artifactId>//;s/<.*//' | tr -d ' ')
        version=$(sed -n '/<\/parent>/,/<\(build\|dependencies\|dependencyManagement\|properties\)>/ p' "$module_dir/pom.xml" | grep -m1 '<version>' | sed 's/.*<version>//;s/<.*//' | tr -d ' ' || true)
        group_id=$(sed -n '/<\/parent>/,/<\(build\|dependencies\|dependencyManagement\|properties\)>/ p' "$module_dir/pom.xml" | grep -m1 '<groupId>' | sed 's/.*<groupId>//;s/<.*//' | tr -d ' ' || true)

        # Fall back to parent values if not specified at project level
        [[ -z "$group_id" ]] && group_id="$parent_group"
        [[ -z "$version" ]] && version="$parent_version"

        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        mkdir -p "$wrapper_dir/src/main/java/org/gridsuite/war"

        # Generate WarInitializer.java
        # Sets spring.config.additional-location to load per-WAR base-uri overrides from
        # an external directory (/config/<ctx>/application.yml). "optional:" prefix means
        # servers with no service references (e.g. report-server) won't fail if the
        # directory doesn't exist. This is the Spring Boot guaranteed way to override
        # config — additional-location properties always win over classpath configs.
        local simple_class="${app_class##*.}"
        local initializer_class="${simple_class/Application/WarInitializer}"
        cat > "$wrapper_dir/src/main/java/org/gridsuite/war/${initializer_class}.java" << JAVA
package org.gridsuite.war;

import ${app_class};
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ${initializer_class} extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(${simple_class}.class)
            .properties("spring.config.additional-location=optional:file:/config/${ctx}/");
    }
}
JAVA

        # Generate wrapper pom.xml from a template: <parent>war-wrappers</parent>,
        # a <dependencyManagement> BOM import of the server's own pom, and a direct
        # <dependencies> entry on the server's classes jar. A plain BOM import only
        # propagates <dependencyManagement>, never <dependencies>, so this alone can
        # silently miss cases where the server pins a version via a direct
        # <dependencies> override (e.g. network-modification-server's
        # gridsuite-network-modification:1.0.0). probe_and_patch_dependencies() (run
        # after this function, once all baseline poms exist) detects such gaps by
        # actually comparing `mvn dependency:list` between the server and this
        # baseline wrapper, and patches this same pom.xml in place with explicit
        # <dependencyManagement> corrections wherever the resolved versions differ.
        local extra_deps=""
        # antlr4 version override: these servers depend on powsybl-open-loadflow which
        # pulls in graphviz-builder → antlr4:4.5.1. But Spring Data JPA's HqlLexer was
        # compiled with antlr4 4.13.0 (ATN version 4). The old antlr4-4.5.1.jar contains
        # ATNDeserializer that only understands ATN version 3, causing:
        #   InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 4
        # Fix: force antlr4 (the full tool jar, which includes the runtime) to 4.13.0.
        # This is excluded from the automated dependency diff (see WRAP_EXCLUDE_GA)
        # so the diff never "corrects" it back to the server's conflicting version.
        local exclude_ga=""
        case "$ctx" in
            loadflow-server|security-analysis-server|sensitivity-analysis-server|network-modification-server)
                extra_deps='
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4</artifactId>
            <version>4.13.0</version>
        </dependency>'
                exclude_ga="org.antlr:antlr4"
                ;;
        esac

        # Cache metadata for the later dependency-diff/patch pass.
        WRAP_MODULE_DIR["$ctx"]="$module_dir"
        WRAP_GROUP_ID["$ctx"]="$group_id"
        WRAP_ARTIFACT_ID["$ctx"]="$artifact_id"
        WRAP_VERSION["$ctx"]="$version"
        WRAP_EXTRA_DEPS["$ctx"]="$extra_deps"
        WRAP_EXCLUDE_GA["$ctx"]="$exclude_ga"

        write_wrapper_pom "$wrapper_dir" "$ctx" "$group_id" "$artifact_id" "$version" "$extra_deps" ""

        modules="$modules        <module>$ctx</module>\n"
        log "  ${ctx}-war -> $module_dir"
    done

    # Generate reactor parent pom
    cat > "$WRAPPERS_DIR/pom.xml" << POM
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gridsuite.war</groupId>
    <artifactId>war-wrappers</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <modules>
$(echo -e "$modules")    </modules>
</project>
POM

    # Generate per-WAR config overrides directly into gen/externalized-war-configs/
    rm -rf "$CONFIG_DIR"
    log "=== Generating externalized WAR additional-configs ==="
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue
        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        generate_local_config_override "$ctx" "$server_folder" "$pom_subpath" "$wrapper_dir"
    done
    (cd "$SCRIPT_DIR" && find gen/externalized-war-configs -type f 2>/dev/null) || true


}

# Picks mvnd (Maven Daemon) when available for faster builds, falling back to
# mvn -q. Sets the global MVN_CMD, used by both the probing and the real build.
pick_mvn_cmd() {
    if command -v mvnd &>/dev/null; then
        MVN_CMD="mvnd"
    else
        MVN_CMD="mvn -T2.0C -q"
    fi
}

# Adds server source modules to the reactor POM (before the wrapper modules), so
# that a single Maven invocation builds server sources + wrapper projects together
# and their classes JARs are available for wrapper dependency resolution without
# needing a separate `mvn install` pass first. Idempotent guard: only injects once,
# since both probe_and_patch_dependencies() and build_wars() run against the same
# reactor POM.
inject_server_modules() {
    local wrapper_pom="$WRAPPERS_DIR/pom.xml"
    grep -q '<!-- Server sources -->' "$wrapper_pom" && return 0

    local server_modules=""
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local rel_path="../../../../../../backend/servers/$server_folder"
        [[ -n "$pom_subpath" ]] && rel_path="$rel_path/$pom_subpath"
        server_modules+="        <module>${rel_path}</module>\n"
    done

    sed -i "s|    <modules>|    <modules>\n        <!-- Server sources -->\n${server_modules}        <!-- WAR wrappers -->|" "$wrapper_pom"
}

# ===========================================================================
# PHASE 1.5: PROBE DEPENDENCY RESOLUTION AND PATCH WRAPPER POMS
# For each server, this compares `mvn dependency:list` of the real server module
# against its baseline wrapper (BOM import only, generated above) to find any
# dependency whose resolved version differs. This happens whenever the server
# pins a version via a direct <dependencies> override that a plain BOM <import>
# cannot see (Maven's <scope>import</scope> only propagates <dependencyManagement>,
# never <dependencies> -- so such an override is otherwise silently lost). Detected
# differences are patched into the wrapper as explicit <dependencyManagement>
# entries, so it resolves every dependency IDENTICALLY to how the real server was
# compiled -- without copying/parsing the server's pom, and without any hand-written
# per-server exception list.
# ===========================================================================
probe_and_patch_dependencies() {
    log "=== Probing dependency resolution (server vs. baseline wrapper) ==="
    log "Running: $MVN_CMD package dependency:list -DskipTests -Dsort=true -DoutputFile=target/dependency-list.txt -fae -f $WRAPPERS_DIR/pom.xml"
    (cd "$WRAPPERS_DIR" && $MVN_CMD package dependency:list -DskipTests -Dsort=true -DoutputFile=target/dependency-list.txt -fae) || true

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local module_dir="${WRAP_MODULE_DIR[$ctx]}"
        local wrapper_dir="$WRAPPERS_DIR/$ctx"
        local server_list="$module_dir/target/dependency-list.txt"
        local wrapper_list="$wrapper_dir/target/dependency-list.txt"

        if [[ ! -f "$server_list" || ! -f "$wrapper_list" ]]; then
            err "  ${ctx}: missing dependency:list output (server=$server_list wrapper=$wrapper_list); skipping correction"
            continue
        fi

        # Diff resolved (compile/runtime/provided) versions by groupId:artifactId,
        # excluding any GA we already force ourselves (e.g. the antlr4 fix), so the
        # diff can't "correct" a deliberate override back to a conflicting version.
        local extra_managed_deps=""
        while IFS=: read -r dep_group dep_artifact dep_ver; do
            [[ -z "$dep_group" ]] && continue
            extra_managed_deps+="
            <dependency>
                <groupId>${dep_group}</groupId>
                <artifactId>${dep_artifact}</artifactId>
                <version>${dep_ver}</version>
            </dependency>"
        done < <(python3 - "$server_list" "$wrapper_list" "${WRAP_EXCLUDE_GA[$ctx]}" << 'PYEOF'
import re
import sys

server_file, wrapper_file, exclude_csv = sys.argv[1], sys.argv[2], sys.argv[3]
excluded = {g for g in exclude_csv.split(',') if g}

LINE_RE = re.compile(r'^\s*([\w.-]+):([\w.-]+):[\w.-]+:([\w.-]+):(\w+)')
RELEVANT_SCOPES = {'compile', 'runtime', 'provided'}


def parse(path):
    deps = {}
    with open(path) as f:
        for line in f:
            m = LINE_RE.match(line)
            if not m:
                continue
            group, artifact, version, scope = m.groups()
            if scope not in RELEVANT_SCOPES:
                continue
            deps[f'{group}:{artifact}'] = version
    return deps


server_deps = parse(server_file)
wrapper_deps = parse(wrapper_file)

for ga, version in sorted(server_deps.items()):
    if ga in excluded:
        continue
    if wrapper_deps.get(ga) != version:
        print(f'{ga}:{version}')
PYEOF
)

        if [[ -n "$extra_managed_deps" ]]; then
            log "  ${ctx}: correcting $(grep -c '<dependency>' <<< "$extra_managed_deps") dependency version(s) to match the server"
            write_wrapper_pom "$wrapper_dir" "$ctx" "${WRAP_GROUP_ID[$ctx]}" "${WRAP_ARTIFACT_ID[$ctx]}" \
                "${WRAP_VERSION[$ctx]}" "${WRAP_EXTRA_DEPS[$ctx]}" "$extra_managed_deps"
        fi

        rm -f "$server_list" "$wrapper_list"
    done

    rm -f "$WRAPPERS_DIR/target/dependency-list.txt"
}

# ===========================================================================
# PHASE 2: BUILD ALL (SINGLE REACTOR)
# Builds ALL server source modules + wrapper projects in one Maven invocation.
# Server source modules are added to the reactor (by inject_server_modules(),
# already done before probe_and_patch_dependencies() ran) so that their classes
# JARs are available in the local repo for wrapper dependency resolution.
# -T2.0C = 2 threads per CPU core for parallel module builds.
# ===========================================================================
build_wars() {
    log "=== Building all with: $MVN_CMD ==="
    log "Running: $MVN_CMD package -DskipTests -f $WRAPPERS_DIR/pom.xml"
    (cd "$WRAPPERS_DIR" && $MVN_CMD package -DskipTests) || {
        err "Reactor build failed"
        return 1
    }

    # Verify
    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue
        if [[ ! -f "$WRAPPERS_DIR/$ctx/target/${ctx}.war" ]]; then
            err "Missing: $WRAPPERS_DIR/$ctx/target/${ctx}.war"
        fi
    done
}

# ===========================================================================
# PHASE 3: COPY WARS TO DOCKER-COMPOSE MOUNT DIR
# ===========================================================================
deploy_to_compose_dirs() {
    log "=== Copying WARs to gen/wars/ ==="
    rm -f "$WEBAPPS_DIR"/*.war 2>/dev/null || true
    mkdir -p "$WEBAPPS_DIR"

    for entry in "${MANIFEST[@]}"; do
        IFS='|' read -r ctx server_folder pom_subpath app_class <<< "$entry"
        should_process "$ctx" || continue

        local war="$WRAPPERS_DIR/$ctx/target/${ctx}.war"
        if [[ -f "$war" ]]; then
            cp "$war" "$WEBAPPS_DIR/"
        else
            err "Missing: $war"
        fi
    done

    (cd "$SCRIPT_DIR" && find gen/wars -maxdepth 1 -name '*.war' -type f 2>/dev/null) || true
    echo ""
    echo "Folders gen/wars/ and gen/externalized-war-configs/ ready for \$ docker compose up"
}

# ===========================================================================
# MAIN
# ===========================================================================
generate_wrappers
pick_mvn_cmd
inject_server_modules
probe_and_patch_dependencies
build_wars
deploy_to_compose_dirs
