{
 "title": "Computations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" },
   {
    "name": "COMPUTATION",
    "query": "loadflow, sa, sensitivityanalysis, ds, shortcircuitanalysis, voltageinit"
   }
  ]
 },
 "panels": [
  {
   "title": "Computation stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Computation rate with success (count/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(app_computation_count_total{type='$COMPUTATION', status='OK'}[$__rate_interval])) by (provider) * 60",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Total time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_global_run_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Model + load equipments time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_run_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation rate with error (count/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(app_computation_count_total{type='$COMPUTATION', status='NOK'}[$__rate_interval])) by (provider) * 60",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation rate with exception (count/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(app_computation_run_seconds_count{type='$COMPUTATION', error!=\"none\"}[$__rate_interval])) by (provider) * 60",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Network save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_network_save_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Results save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_results_save_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report send time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_report_send_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report delete time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_report_delete_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "Computation count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Queued computation",
   "type": "timeseries",
   "description": "Messages with ready state count in rabbitmq queue.\nDisplay how many calculation are waiting to be ran.\nCalculation currently running are not counted here",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages_ready{queue=~\".*.${COMPUTATION}..*\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Current computation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(app_computation_current_count{type='$COMPUTATION'}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}