{
 "title": "Application pools",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Network diagram generation pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_diagram_tasks_pool_current", "legendFormat": "{{type}}" },
    { "expr": "app_diagram_tasks_pool_pending", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Network modification pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_network_modification_tasks_pool_current",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "app_network_modification_tasks_pool_pending",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network conversion pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app_conversion_tasks_pool_current",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "app_conversion_tasks_pool_pending",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Geo data fetch pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "app_geo_data_tasks_pool_current",
     "legendFormat": "current"
    },
    {
     "expr": "app_geo_data_tasks_pool_pending",
     "legendFormat": "pending"
    }
   ]
  }
 ]
}