{
 "title": "Computations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" },
   {
    "name": "COMPUTATION",
    "query": "loadflow, sa, sensi, dynamicSimulation, shortcircuit, voltageInit"
   }
  ]
 },
 "panels": [
  {
   "title": "Computation reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Computation with success count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(app_computation_count_total{type='$COMPUTATION', status='OK'}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_run_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation with error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(app_computation_count_total{type='$COMPUTATION', status='NOK'}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation with exception count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(app_computation_run_seconds_count{type='$COMPUTATION', error!=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Network save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_network_save_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Results save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_results_save_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report send time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_report_send_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report delete time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_computation_report_delete_seconds_max{type='$COMPUTATION', error=\"none\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}