{
 "title": "Network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network import/export reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "import conversion time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_conversion_import_seconds_max{namespace=\"$namespace\", error=\"none\"}"
    }
   ]
  },
  {
   "title": "export conversion time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_conversion_export_seconds_max{namespace=\"$namespace\", error=\"none\"}"
    }
   ]
  },
  {
   "title": "Failed conversion count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "app_conversion_failed_total{namespace=\"$namespace\", error=\"none\"}"
    }
   ]
  }
 ]
}