{
 "title": "LoadFlow",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_loadflow_run_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "app_loadflow_run_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max (Load network)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app_loadflow_network_load_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Save network)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "app_loadflow_network_save_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Save results)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "app_loadflow_results_save_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Send report)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "app_loadflow_report_send_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Delete report)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "app_loadflow_report_delete_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}