{
 "title": "Database connection pools",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_pending) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}