{
 "title": "Database connection pools by job",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{job=\"$job\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum(hikaricp_connections_idle{job=\"$job\"})",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "sum(hikaricp_connections_pending{job=\"$job\"})",
     "legendFormat": "Pending threads"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Connections per pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"$job\"}",
     "legendFormat": "Active connections {{ pod }}"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"$job\"}",
     "legendFormat": "Pending threads {{ pod }}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_timeout_total{job=\"$job\"})"
    }
   ]
  },
  { "title": "Connection durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Connections Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_max{job=\"$job\"}",
     "legendFormat": "Usage time {{ pod }}"
    },
    {
     "expr": "hikaricp_connections_creation_seconds_max{job=\"$job\"}",
     "legendFormat": "Creation time {{ pod }}"
    },
    {
     "expr": "hikaricp_connections_acquire_seconds_max{job=\"$job\"}",
     "legendFormat": "Connection acquired {{ pod }}"
    }
   ]
  }
 ]
}