{
 "title": "JVM metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of full GC/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[1m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max full GC time on time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(job) (max_over_time(jvm_gc_pause_seconds_max{action=\"end of major GC\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (increase(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC pressure",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum[1m])) by (pod) ",
     "legendFormat": "{{pod}}"
    },
    { "expr": "0.01", "legendFormat": "__auto" }
   ]
  }
 ]
}