{
 "title": "Network store server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Get resource time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_get_seconds_max) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Get all resources time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_get_all_seconds_max) by (resource_type)",
     "legendFormat": "{{resource_type}} "
    }
   ]
  },
  {
   "title": "Create all resources time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_create_all_seconds_max) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Remove all resources time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_remove_all_seconds_max) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Update all resources time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_update_all_seconds_max) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Clone network time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_clone_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Normalized metrics (per resource max)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Get all resources (per resource max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_get_all_per_resource_seconds_max{empty=\"false\"}) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Remove all resources (per resource max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_remove_all_per_resource_seconds_max{empty=\"false\"}) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Create all resources (per resource max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_create_all_per_resource_seconds_max{empty=\"false\"}) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Clone network (per variant max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_clone_per_variant_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update all resources (per resource max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_network_store_server_update_all_per_resource_seconds_max{empty=\"false\"}) by (resource_type)",
     "legendFormat": "{{resource_type}}"
    }
   ]
  }
 ]
}