{
 "title": "Network modifications",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Network modification reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Modification (unitary) time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "app_network_modification_apply_seconds_max{error=\"none\"}",
     "legendFormat": "{{modification_type}}"
    }
   ]
  },
  {
   "title": "Modification (unitary) with success count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "app_network_modification_apply_seconds_count{error=\"none\"}",
     "legendFormat": "{{modification_type}}"
    }
   ]
  },
  {
   "title": "Modifications (group) time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "app_network_modification_build_seconds_max{error=\"none\"}"
    }
   ]
  },
  {
   "title": "Modifications (group) with success count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "app_network_modification_build_seconds_count{error=\"none\"}"
    }
   ]
  }
 ]
}