{
 "title": "Pod CPU monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "pod_filter" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\".*$pod_filter.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{pod=~\".*$pod_filter.*\"}",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{pod=~\".*$pod_filter.*\"}",
     "legendFormat": "CPU limits"
    }
   ]
  },
  {
   "title": "CPU time throttled",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\".*$pod_filter.*\", container=\"main\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentage of throttled CPU periods",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\".*$pod_filter.*\", container=\"main\"}[5m])\n  /\nrate(container_cpu_cfs_periods_total{pod=~\".*$pod_filter.*\", container=\"main\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC pause",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{pod=~\".*$pod_filter.*\"}[1m])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}