{
 "title": "Pods supervision",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values({service=\"kube-prometheus-stack-kubelet\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pods status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pods ready" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kube_replicaset_status_ready_replicas) and kube_replicaset_spec_replicas>0)",
     "legendFormat": "{{replicaset}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pods not ready" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kube_replicaset_spec_replicas - kube_replicaset_status_ready_replicas) and kube_replicaset_spec_replicas>0)",
     "legendFormat": "{{replicaset}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_replicaset_spec_replicas - kube_replicaset_status_ready_replicas)>0",
     "legendFormat": "{{replicaset}}"
    }
   ]
  },
  { "title": "Pods info and restarts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{service=\"$service\", container=\"main\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{service=\"$service\", container=\"main\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (pod)"
    },
    {
     "expr": "kube_pod_created{pod!~\".*cronjob.*\"} * 1000"
    },
    {
     "expr": "sum(tomcat_threads_busy_threads) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tomcat_threads_current_threads) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tomcat_threads_config_max_threads) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total"
    },
    {
     "expr": "kube_pod_container_status_last_terminated_reason"
    }
   ]
  },
  {
   "title": "Gateway total connections",
   "type": "timeseries",
   "description": "This panel display Gateway total connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "reactor_netty_http_server_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway active connections",
   "type": "timeseries",
   "description": "This panel display Gateway active connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "reactor_netty_http_server_connections_active",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed infos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods not ready",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum((kube_replicaset_spec_replicas - kube_replicaset_status_ready_replicas) and kube_replicaset_spec_replicas>0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods container restarts rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{pod!~\".*cronjob.*\"}[1h])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OOMKilled events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "(kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}[10m]) == 1",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}