{
 "title": "Security Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Computation time (max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_security_analysis_run_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_security_analysis_run_seconds_count",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Run queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages{queue=~\"sa.run.*\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Results save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "app_security_analysis_result_save_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Network load time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "app_security_analysis_network_load_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report send time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "app_security_analysis_report_send_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report delete time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "app_security_analysis_report_delete_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}