{
 "title": "Sensitivity Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Computation time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_run_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Computation count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_run_seconds_count",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Network load time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_network_load_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Network save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_network_save_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Results save time (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_results_save_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report send time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_report_send_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Report delete time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "app_sensitivity_analysis_report_delete_seconds_max",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}