{
 "title": "Service's pods metrics",
 "description": "Metrics of pods composing a service (server, webapp, etc...)",
 "tags": [
  "kubernetes",
  "cadvisor",
  "pod",
  "micrometer",
  "springboot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_owner,cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_owner{cluster_name=\"$cluster_name\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_replicaset_owner{cluster_name=\"$cluster_name\", namespace=\"$namespace\", owner_kind=\"Deployment\"},owner_name)"
    }
   },
   {
    "name": "replicatset",
    "label": "ReplicaSets",
    "query": {
     "query": "label_values(kube_replicaset_owner{cluster_name=\"$cluster_name\", namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=~\"$deployment\"},replicaset)"
    }
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values(kube_pod_owner{cluster_name=\"$cluster_name\", namespace=\"$namespace\", owner_kind=\"ReplicaSet\", owner_name=~\"$replicatset\"},pod)"
    }
   },
   { "name": "service", "label": "Service", "query": "${VAR_SERVICE}" },
   { "name": "container", "label": "Container", "query": "${VAR_CONTAINER}" },
   { "name": "packets_or_bytes", "label": "I/O (netw)", "query": "bytes,packets" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Some notes for users",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Notes:<br/>\n<ul>\n  <li>Only show pods, no jobs/cronjob/...</li>\n  <li>Show metrics at pod level, combine containers and processes values.</li>\n</ul>"
   }
  },
  {
   "title": "System load (avg. 1m)",
   "type": "timeseries",
   "description": "CPU system load of pods over sliding 60 sec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg_over_time(system_load_average_1m{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Nb CPU cores",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(system_cpu_count{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", container=\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU alloction share",
   "type": "piechart",
   "description": "Informs fair-share CPU competition in shared environments.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(container_spec_cpu_shares{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Quick view of ${pods}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "pods" },
  {
   "title": "Last seen",
   "type": "stat",
   "description": "TODO if >60s then red",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(container_last_seen{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container!=\"POD\", pod=~\"$pods\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max without(name, id) (container_memory_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_max_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
     "legendFormat": "max_recorded"
    },
    {
     "expr": "max without(name, id) (container_spec_memory_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max without(name, id) (container_memory_swap{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max without(name, id) (container_processes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max without(name, id) (container_threads{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
     "legendFormat": "current"
    },
    {
     "expr": "container_threads_max{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "FS usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max without(name, id) (container_fs_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "container_fs_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Last start duration",
   "type": "stat",
   "description": "Duration of the last pod start.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(container_start_time_seconds{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container!=\"POD\", pod=~\"$pods\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Details of pod $pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "pods",
   "collapsed": true,
   "panels": [
    {
     "title": "Last seen",
     "type": "stat",
     "description": "TODO if >60s then red",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(container_last_seen{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container!=\"POD\", pod=~\"$pods\"}[$__interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "system_cpu_usage{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max without(name, id) (container_memory_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "container_memory_max_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
       "legendFormat": "max_recorded"
      },
      {
       "expr": "container_spec_memory_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Swap usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max without(name, id) (container_memory_swap{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "last_over_time(container_spec_memory_swap_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max without(name, id) (container_processes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max without(name, id) (container_threads{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "current"
      },
      {
       "expr": "container_threads_max{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "FS usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max without(name, id) (ntainer_fs_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "container_fs_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Files descriptors",
     "type": "stat",
     "description": "Number of files handled (open, read, write ...)",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max without(name, id) (container_file_descriptors{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Last start duration",
     "type": "stat",
     "description": "Duration of the last pod start.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(container_start_time_seconds{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container!=\"POD\", pod=~\"$pods\"}[$__interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "* user: CPU time spent in user space\n* system: CPU time spent in kernel/system space",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max without(name, id) (increase(container_cpu_system_seconds_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval]))",
       "legendFormat": "system"
      },
      {
       "expr": "max without(name, id) (increase(container_cpu_user_seconds_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval]))",
       "legendFormat": "user"
      },
      {
       "expr": "max without(name, id) (increase(container_cpu_usage_seconds_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "CPU configured limits",
     "type": "stat",
     "description": "How much CPU the container is allowed to use (as set by k8s).\n* **period**: Length of a single CPU quota period _(typically 100ms)_\n* **quota**: Total CPU time available in each period _(e.g., 200,000μs = 2 CPUs)_\n* **shares**: Relative CPU share weight for proportional CPU allocation (used by CFS in shared environments)",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "last_over_time(container_spec_cpu_period{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__interval])",
       "legendFormat": "period"
      },
      {
       "expr": "last_over_time(container_spec_cpu_quota{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__interval])",
       "legendFormat": "quota"
      },
      {
       "expr": "last_over_time(container_spec_cpu_shares{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__interval])",
       "legendFormat": "shares"
      }
     ]
    },
    {
     "title": "CPU CFS",
     "type": "stat",
     "description": "* **periods**: Total number of scheduling periods (from CFS scheduler)\n* **throttled_periods**: How many times the container hit CPU quota\n* **throttled_seconds**: How much time the container was throttled",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_periods_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "periods"
      },
      {
       "expr": "increase(container_cpu_cfs_throttled_periods_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "throttled_periods"
      },
      {
       "expr": "increase(container_cpu_cfs_throttled_seconds_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "throttled_seconds"
      },
      {
       "expr": "container_spec_cpu_period{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
       "legendFormat": "periods_max"
      }
     ]
    },
    {
     "title": "CPU CFS periods",
     "type": "stat",
     "description": "CPU time usage by pod in allowed limit.",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_periods_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "current"
      },
      {
       "expr": "container_spec_cpu_period{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}",
       "legendFormat": "max"
      },
      { "expression": "$Current / $Max", "type": "math" }
     ]
    },
    {
     "title": "Is CPU being throttled?",
     "type": "stat",
     "description": "If throttled time is high, container is limited by CPU quota.",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "increase(container_cpu_cfs_throttled_seconds_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "throttled"
      },
      {
       "expr": "increase(container_cpu_usage_seconds_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "usage"
      },
      { "expression": "${Throttled}/${Usage}", "type": "math" }
     ]
    },
    {
     "title": "RAM usage (detail)",
     "type": "timeseries",
     "description": "Breakdown of RAM usage:\n- Memory used as cache (page cache)\n- Resident Set Size: non-swappable memory used by the container _(amount of anonymous and swap cache memory, including transparent hugepages)_\n- The amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max without(name, id) (container_memory_rss{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "rss"
      },
      {
       "expr": "max without(name, id) (container_memory_mapped_file{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "map_file"
      },
      {
       "expr": "max without(name, id) (container_memory_cache{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "cache"
      },
      {
       "expr": "max without(name, id) (container_memory_working_set_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "wss"
      },
      {
       "expr": "max without(name, id) (container_spec_memory_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "limit"
      },
      {
       "expr": "max without(name, id) (container_memory_usage_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "max without(name, id) (container_spec_memory_reservation_limit_bytes{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "reserved"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "description": "Receive and transmit data over network.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_${packets_or_bytes}_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "{{interface}}-${packets_or_bytes}-recv"
      },
      {
       "expr": "rate(container_network_transmit_${packets_or_bytes}_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "{{interface}}-${packets_or_bytes}-send"
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_errors_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "{{pod}}-{{interface}}-recv"
      },
      {
       "expr": "rate(container_network_transmit_errors_total{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", pod=~\"$pods\"}[$__rate_interval])",
       "legendFormat": "{{pod}}-{{interface}}-send"
      }
     ]
    },
    {
     "title": "Sockets",
     "type": "timeseries",
     "description": "Number of open TCP/IP sockets",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max without(name, id) (container_sockets{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=\"$service\", container=\"$container\", pod=~\"$pods\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "HTTP connections",
     "type": "timeseries",
     "description": "__is it server or client for tomcat?__\n\nTomcat ThreadPool:\n* `*-tomcat-*-active`: number of connections the connector has handled\n* `*-tomcat-*-keepalive`: requests that can go through the socket before the socket is closed, and reopened for the next request.\n\nNetty Reactor:\n* `*-netty-*`: __?__ \n* `*-netty-*-active`: connections that have been successfully acquired and are in active use.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_connections_current_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
       "legendFormat": "{{pod}}-tomcat-{{name}}-active"
      },
      {
       "expr": "tomcat_connections_keepalive_current_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
       "legendFormat": "{{pod}}-tomcat-{{name}}-keepalive"
      },
      {
       "expr": "tomcat_connections_config_max_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
       "legendFormat": "{{pod}}-tomcat-{{name}}-max"
      },
      {
       "expr": "reactor_netty_http_server_connections_active{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
       "legendFormat": "{{pod}}-netty-{{uri}}-active"
      },
      {
       "expr": "reactor_netty_http_server_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", container=\"$container\", service=~\"$deployment\", pod=~\"$pods\"}",
       "legendFormat": "{{pod}}-netty-{{uri}}"
      }
     ]
    },
    {
     "title": "Database connections (connections pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hikaricp_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-hikaricp-{{pool}}"
      },
      {
       "expr": "hikaricp_connections_active{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-hikaricp-{{pool}}-active"
      },
      {
       "expr": "hikaricp_connections_idle{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-hikaricp-{{pool}}-idle"
      },
      {
       "expr": "hikaricp_connections_pending{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-hikaricp-{{pool}}-pending"
      },
      {
       "expr": "r2dbc_pool_acquired_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-r2dbc-{{name}}-acquired"
      },
      {
       "expr": "r2dbc_pool_allocated_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-r2dbc-{{name}}-allocated"
      },
      {
       "expr": "r2dbc_pool_idle_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-r2dbc-{{name}}-idle"
      },
      {
       "expr": "r2dbc_pool_pending_connections{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-r2dbc-{{name}}-pending"
      }
     ]
    },
    {
     "title": "Database connections (JDBC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jdbc_connections_active{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-jdbc-{{name}}-active"
      },
      {
       "expr": "jdbc_connections_idle{cluster_name=\"$cluster_name\", namespace=\"$namespace\", service=~\"$deployment\", pod=~\"$pods\", container=\"$container\"}",
       "legendFormat": "{{pod}}-jdbc-{{name}}-idle"
      }
     ]
    }
   ]
  }
 ]
}