{
 "title": "State estimation orchestrator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "State estimation orchestrator reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Import input file in case-server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_input_case_import_seconds_max"
    }
   ]
  },
  {
   "title": "Create network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_create_network_seconds_max"
    }
   ]
  },
  {
   "title": "Apply modifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_modifications_apply_seconds_max"
    }
   ]
  },
  {
   "title": "State estimation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_stateestimation_run_seconds_max"
    }
   ]
  },
  {
   "title": "Loadflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_loadflow_run_seconds_max"
    }
   ]
  },
  {
   "title": "Export network to BIIDM format output file",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_network_export_seconds_max"
    }
   ]
  },
  {
   "title": "Store output file in case-server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stateestimation_orchestrator_output_case_import_seconds_max"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(stateestimation_orchestrator_total_time_seconds_max + stateestimation_orchestrator_input_case_import_seconds_max)"
    }
   ]
  }
 ]
}