{
 "title": "Users",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSrc Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "User reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "User count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(count by (user) (app_users)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Connexion count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(app_users) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number of connections per user (${__to:date:DD/MM/YYYY HH:mm})",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sum by (user) (app_users)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "List of users (${__from:date:DD/MM/YYYY HH:mm} → ${__to:date:DD/MM/YYYY HH:mm})",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "app_users{user!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}